PREFIX : <http://example.com/base/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fo: <http://www.w3.org/1999/XSL/Format#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpr: <http://dbpedia.org/resource/>
PREFIX dbpo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# 1) Quais as propriedades que Dan Brickley usou para descrever a si mesmo? Faça duas versões de solução: 

# (i) mostrar as triplas;
SELECT ?s ?o ?p
FROM <http://danbri.org/foaf.rdf>
WHERE {
    ?s ?o ?p .
    ?s foaf:nick ?nick .
    filter regex(str(?nick), "^danbri$", "i") .
}

# (iii) mostrar apenas as propriedades (sem repetições).
SELECT DISTINCT ?o
FROM <http://danbri.org/foaf.rdf>
WHERE {
    <https://danbri.org/foaf.rdf#danbri> ?o ?p .
}


# 2) Mostre o(s) e-mail(s) de Dan Brickley.

SELECT ?mail
FROM <http://danbri.org/foaf.rdf>
WHERE {
    <https://danbri.org/foaf.rdf#danbri> foaf:mbox ?mail
}

# 3) Mostre, em ordem alfabética, os nomes dos amigos de Dan Brickley.

SELECT ?nomeDosAmigos
FROM <http://danbri.org/foaf.rdf>
WHERE {
    <https://danbri.org/foaf.rdf#danbri> foaf:knows ?amigos .
    ?amigos foaf:name ?nomeDosAmigos .
}
ORDER BY ASC (?nomeDosAmigos)

# 4) Encontre as pessoas (retorne seus nomes e IRIs dos recursos que as representam) que foram mencionadas no arquivo FOAF de Dan Brickley, ordenando os resultados em ordem alfabética do nome dessas pessoas. A consulta deve exibir apenas os resultados do 11o ao 20o.

SELECT ?nomeDasPessoas ?iris
FROM <http://danbri.org/foaf.rdf>
WHERE {
    ?pessoas rdf:type foaf:Person .
    ?pessoas foaf:name ?nomeDasPessoas .
    ?pessoas ?iris ?p .
}
ORDER BY ASC (?nomeDasPessoas)
LIMIT 10 OFFSET 10

# 5) Encontre os amigos de Dan Brickley que estão relacionados à W3C (dica: use o e-mail para filtrar os amigos desejados). Apresente o nome e e-mail desses amigos.

SELECT ?nomeDosAmigos ?emailDosAmigos
FROM <http://danbri.org/foaf.rdf>
WHERE {
    <https://danbri.org/foaf.rdf#danbri> foaf:knows ?amigos .
    ?amigos foaf:name ?nomeDosAmigos .
    ?amigos foaf:mbox ?emailDosAmigos .
    FILTER regex(str(?emailDosAmigos), "@w3.org$", "i") .
}

# 6) O que foi dito sobre Tim Berners-Lee no arquivo FOAF de Dan Brickley? Sua consulta deve ser case-insensitive para selecionar o nome de Tim Berners-Lee.

SELECT DISTINCT ?o ?p
FROM <http://danbri.org/foaf.rdf>
WHERE {
    ?s ?o ?p .
    ?s foaf:name ?name
    filter regex(str(?name),"^Tim Berners-Lee$", "i") .
}

# 7) Encontre todos os formatos de fotos usados por amigos de Dan Brickley.

SELECT ?nomeDosAmigos ?formatoDeFoto
FROM <http://danbri.org/foaf.rdf>
WHERE {
    <https://danbri.org/foaf.rdf#danbri> foaf:knows ?amigos .
    ?amigos foaf:name ?nomeDosAmigos .
    ?amigos foaf:img ?formatoDeFoto .
}

# 8) Encontre as relações de amizade descritas no arquivo de Dan Brickley que não o envolvem diretamente.



# 9) Mostre todos os literais que possuem definição de idioma explícito como inglês (“en”).

SELECT ?literais
FROM <http://danbri.org/foaf.rdf>
WHERE {
    ?s ?o ?literais .
    filter(langMatches(lang(?literais), "en")) .
}